# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 014d27994fe93252f9dbfdff62ffe7b88b3fc8501fe93bbe79f50551e7cef1e7a2ee5f16d97877ec971f375e8c17014ccc4ffe5da91b0afa00a3445b693c4e9b

test:
  secret_key_base: 07e59cbe20ebac10db06b1076a110046cbe05bff7efc7beb17935e54d42ef783b46492da97362b9c9013bc8ac81f48bd5be672b1e195cb3647ca48405119daa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
